### ISSUE TITLE
TODO: 

### ISSUE THREAD

**Issue by Scraayp** [Scraayp/bhcshop#1]
# Main page
- [ ] Meta tags and the full head system
- [x] Navbar
- [x] Footer

# Main System
- [x] Setup netlify
- [ ] Setup responsive shit for mobile etc..
- [x] Vue setup with tailwind for the admin page and webshop
- [ ] Login system on the admin page
- [ ] Contact page on the admin page
- [ ] Blogs system with possible system to let users create websites just with content

# Fix
- [x] Colors
- [ ] Navbar responsive
